CREATE TABLE REPRESENTANTE ( 
	REPRESENTANTEID NUMBER PRIMARY KEY, 
	NOMEREPRESENTANTE VARCHAR2(80) NOT NULL, 
	CPF VARCHAR2(14) NOT NULL
); 
 
CREATE SEQUENCE REPRESENTANTE_ID_SEQ;  
 
CREATE OR REPLACE TRIGGER TR_SEQ_REPRESENTANTE BEFORE INSERT ON REPRESENTANTE FOR EACH ROW  
BEGIN 
	SELECT REPRESENTANTE_ID_SEQ.NEXTVAL INTO :new.REPRESENTANTEID FROM dual; 
END; 
 
--DROP TRIGGER TR_SEQ_REPRESENTANTE; 
--DROP SEQUENCE REPRESENTANTE_ID_SEQ; 
--DROP TABLE REPRESENTANTE;   
